sudo: required
services:
  - docker

  before_install:
    - docker build -t adeshadk/docker-react -f Dockerfile.dev .

  scripts:
    - docker build -t adeshadk/docker-react npm run test -- --coverage
    