sudo: required
services:
  - docker

before_install:
    - docker build -t adeshadk/docker-react -f Dockerfile.dev .

script:
    - docker run adeshadk/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-685919621674"
  bucket_path: "docker-react"
  on:
     branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: "$SECRET_KEY"
